# Generated by Django 5.2.6 on 2025-09-06 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.libro')),
            ],
        ),
    ]
