# Generated by Django 5.2.6 on 2025-09-06 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_editorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.editorial')),
            ],
        ),
    ]
